name: Sync with ameba-rtos-pro2

on:
  repository_dispatch:
    types: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync with ameba-rtos-pro2
        run: |
          git remote add origin https://github.com/M-ichae-l/ameba-rtos-pro2.git
          git fetch origin
          git merge origin/main
          git push origin main
